#técharger go pour la compilation
FROM golang:1.24-alpine

#houni yssir kl chy
WORKDIR /app

# copier la liste des dépendances
COPY go.mod go.sum ./
#télécharger les dépendances
RUN go mod download

#copie ml code source
COPY . .

#Compile ton code en un fichier executable appelé api
RUN go build -o api ./cmd/...

#il port
EXPOSE 8000

#tlanci li programme
CMD ["./api"]
